[package]
name = "pgblade-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "A fast, native PostgreSQL workbench"
repository = "https://github.com/LucaGerlich/pgblade"
authors = ["Luca Gerlich"]

[package.metadata.bundle]
name = "PgBlade"
identifier = "com.lucagerlich.pgblade"
category = "Developer Tool"
short_description = "A fast, native PostgreSQL workbench"

[[bin]]
name = "pgblade"
path = "src/main.rs"

[dependencies]
pgblade-core = { workspace = true }
pgblade-ui = { workspace = true }
gpui = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
