[package]
name = "pgblade-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pgblade-core = { workspace = true }
pgblade-postgres = { workspace = true }
pgblade-security = { workspace = true }
gpui = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
